# Generated by Django 3.1.4 on 2021-01-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210125_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likedposts',
            field=models.TextField(default='[]'),
        ),
    ]
